# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AXmDlfj_nbW8jFIhXwHCl-HnYXf57FjG
"""

print('\033[30m'+'Hello World'+'\033[0m')

print('\033[36m'+'Hello World'+'\033[0m')

print('\033[36m'+'1 Hello World'+'\033[1m')
print('\033[30m'+'2 Hello World'+'\033[0m')

print('\033[30m'+'セキュリティが甘そうだと感じたほうの数字を入力してください'+'\033[0m')

weak = input('')
weak = int(weak)


if weak == 1:
 import getpass
 pw =getpass.getpass()

